### DISCUSSION TITLE
Simulator fetching to localhost services throw the error [TypeError: Network request failed]

### DISCUSSION THREAD

**Discussion by ivandata** [infinitered/ignite#2672] [Q&A] [answered]
Hello everyone! 
First, thank you for this boilerplate. It is amazing! 

I'm using ignite with expo, and I'm stuck with local API settings. I want to make requests from simulator to my local services using `apisauce` (but tried also pure fetch). My backend services and APIs running in docker on local host with certificates. I'm using Caddy server to redirects calls from localhost to docker images.

Curl, postman e.t.c. works fine. Web version also successfully receive responses, while IOS simulator throws error `[TypeError: Network request failed]`.

Looks like a simulator should be configured somehow to make requests to a local server, but I can't find information about that.
My compose file
```
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - ./localhost.crt:/etc/caddy/localhost.crt
      - ./localhost.key:/etc/caddy/localhost.key
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - core-network
    depends_on:
      - core
      - analyzer
    restart: unless-stopped
```
Caddyfile
```
local.chemiapp.com {
    tls /etc/caddy/localhost.crt /etc/caddy/localhost.key

	header {
		Access-Control-Allow-Origin *
		Access-Control-Allow-Credentials true
		Access-Control-Allow-Methods
		Access-Control-Allow-Headers Content-Type, Authorization
		defer
	}

	handle_path /v2/* {
		reverse_proxy core:1027 {
			header_down -Access-Control-Allow-Origin
		}
	}

	handle_path /v1/* {
		reverse_proxy analyzer:1024
	}
}
```

my host file
```
##
127.0.0.1       localhost
127.0.0.1 local.chemiapp.com
```

Surely someone has faced the same problem and knows a solution. I would very appreciate for any help!
