### ISSUE TITLE
Thoughts on changing font size location

### ISSUE THREAD

**Issue by markrickert** [infinitered/ignite#49]
I find myself doing this very often:

```css
  title: {
    fontFamily: Fonts.bold,
    fontSize: Metrics.fonts.medium,
    color: Colors.charcoal
  },
```

I think it would feel a lot "cleaner" to do this:

```css
  title: {
    fontFamily: Fonts.bold,
    fontSize: Fonts.size.medium,
    color: Colors.charcoal
  },
```

It would be a relatively easy change. When i thing of "font size" i don't think of the "metrics" object, i think of the "font" object.

### Make sure verify the following before submitting an issue.

- [x] Issue does not already exist
- [x] You have example code or some other reproduce experiment that we can verify
